version: '3'
services:
    nginx:
        image: nginx-frontend
        build: 
          context: .
        volumes:
          - /home/kerem/nginx/data:/usr/share/nginx/html
        ports:
            - 80:80
        networks: 
            - mynetwork
    firstapp:
        image: kerembilim/first-app
        ports:
            - 3000:3000
        networks:
            - mynetwork
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root123
        volumes:
            - ./mongo:/data/db
        ports:
            - 27017:27017
        networks:
            - mynetwork
    secondapp:
        image: kerembilim/second-app
        ports:
            - 4000:4000
        networks:
            - mynetwork
networks: 
    mynetwork: